### PR TITLE
Adding MDCS scripts and config files for generating mosaic datasets

### PR DESCRIPTION
**Pull request by hjkristenson**
Add a directory containing the files associated with Esri's MDCS workflow for generating mosaic datasets. These mosaic datasets are used by the ArcGIS Image Server or Dedicated Imagery service to publish image services.

### CODE REVIEW

**Comment by jhkennedy** [comment]
Because ESRI is including the Apache header in their files, we should modify any file with the header like:

```diff
#------------------------------------------------------------------------------
# Copyright 2013 Esri
+ # Modifications Copyright 2021 Alaska Satellite Facility 
```

**Review by hjkristenson — COMMENTED** [review]
@jhkennedy That explains why when I made the same changes and tried to push them I was prompted to either merge or not push them. :)
Many of the .py files have not actually been changed. Should I only add the modification language to those that have?

**Comment by jhkennedy** [comment]
@hjkristenson which files haven't been updated? All the python files that had the Ersi copyright should have been updated. You might just need to pull

**Comment by hjkristenson** [comment]
@jhkennedy *Your* corrections were all applied. I meant that I hadn't made any code changes to many of the .py files. Most of the adjustments are applied to the .xml or .bat files. I thought perhaps I should only add the modification language to the .py files that had actually been modified.

**Comment by jhkennedy** [comment]
@hjkristenson Ah, I understand. I think broadly re-applying the copyright for any modifications (whether or not they exist) is the right approach since we're "redistributing" them and then we don't have to worry about it in the future. We can track modification ourselves, or if we want to state specific changes, we can include a `CHANGES.diff` file

**Comment by hjkristenson** [comment]
@jhkennedy Great. That sounds good. Thanks!

**Pull request merged**
